language: java
jdk:
  - oraclejdk8
services:
  - redis-server
# to overcome travis problems with gradlew, see: https://joerglenhard.wordpress.com/2013/10/01/using-travis-ci-with-gradle-wrapper/
before_install:
 - chmod +x gradlew
